[GlobalDefaults DeviceProfile]
; OptionalLODBias=1 将最高一级 mip (mip0) 剥离到 optional bulkdata package
; 这些 optional bulkdata 会被打包到 OnDemandOptionalPak，运行时按需下载
+TextureLODGroups=(Group=TEXTUREGROUP_World,OptionalLODBias=1)
+TextureLODGroups=(Group=TEXTUREGROUP_WorldNormalMap,OptionalLODBias=1)
+TextureLODGroups=(Group=TEXTUREGROUP_WorldSpecular,OptionalLODBias=1)
+TextureLODGroups=(Group=TEXTUREGROUP_Character,OptionalLODBias=1)
+TextureLODGroups=(Group=TEXTUREGROUP_CharacterNormalMap,OptionalLODBias=1)
+TextureLODGroups=(Group=TEXTUREGROUP_CharacterSpecular,OptionalLODBias=1)
+TextureLODGroups=(Group=TEXTUREGROUP_Vehicle,OptionalLODBias=1)
+TextureLODGroups=(Group=TEXTUREGROUP_VehicleNormalMap,OptionalLODBias=1)
+TextureLODGroups=(Group=TEXTUREGROUP_VehicleSpecular,OptionalLODBias=1)
+TextureLODGroups=(Group=TEXTUREGROUP_Weapon,OptionalLODBias=1)
+TextureLODGroups=(Group=TEXTUREGROUP_WeaponNormalMap,OptionalLODBias=1)
+TextureLODGroups=(Group=TEXTUREGROUP_WeaponSpecular,OptionalLODBias=1)
